name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install dependencies
      run: if [ -f package.json ]; then pnpm install; fi

    - name: Build
      run: if [ -f package.json ]; then pnpm run build --if-present; fi

    - name: Test
      run: if [ -f package.json ]; then pnpm test; fi
